
#共通配置
test:
  name: hool
  maker: song
  timeout: 10
  datasize: 10MB
  port: 10
  list: [1,2,3,7,9]
#  引用polxml标签元素
  version: @project.version@
#spring:
#  datasource:
#    durid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/springtest
#      username: root
#      password: scm521
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    druid:
      username: root
      password: scm521
      url: jdbc:mysql://localhost:3306/springtest
      driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: pro
    group:
      "pro": proR,proB
      "dev": devR,devB
#      排除热部署目录
#  关闭热部署
  devtools:
    restart:
      exclude: static/**
      enabled: true
#  redis
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      cache-null-values: false
      time-to-live: 30s
    type: redis
#mail 开启ssl，密码为应用专用密码
  mail:
    host: smtp.gmail.com
    username: scm19971114@gmail.com
    password: xsqxnneamabkeivb
    properties:
      mail:
        smtp:
          ssl:
            enable: true



    protocol: smtp
#    监控
  boot:
    admin:
      client:
        url: http://localhost:8081
#log设置
logging:
  level:
    root: info
    info: debug
#    分组
  group:
    info: com.scm.demo
#    格式
  pattern:
#    d时间 5位数 不够空格  p 级别 m 信息
    console: "%d %5p %m %n"
  file:
    name: server.log
  logback:
    rollingpolicy:
      file-name-pattern: D:/server.%d.%i.log
      max-file-size: 4KB
      max-history: 1
#      监控内容
management:
  endpoint:
    health:
      show-details: always
      #   全部
  endpoints:
    web:
      exposure:
        include: "*"